application:
  port: 8000
  # You will need to set the APP_APPLICATION__HMAC_SECRET env variable on Digital Ocean as well for production
  hmac_secret: "zJDoc4!jD3XggoHGS97t#kob9sn9je8yaR&p#YebzJDoc4!jD3XggoHGS97t#kob9sn9je8yaR&p#Yeb"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "http://127.0.0.1"
  sender_email: "test@example.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 3000
